name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          'Hello there ğŸ‘‹
          Thanks for submitting your first issue to the Quickemu project ğŸ›
          We'll try and take a look at your issue soon â²

          In the meantime you might want to join the [Wimpys World Discord](https://wimpysworld.io/discord) where
          we have a large community of Linux ğŸ§ enthusiasts and passionate open source
          developers ğŸ§‘â€ğŸ’»

          You might also be interested in following [Wimpys World Twitch ğŸ“¡ channel](https://twitch.tv/WimpysWorld)
          where Wimpy streams let's code video, including this project, several
          times a week. A back catalog of past live stream and other Linux related content
          is available on [Wimpys World YouTube ğŸ“º channel](https://youtube.com/WimpysWorld).'
        pr-message: |
          'Hello there ğŸ‘‹
          Thanks for submitting your first pull request to the Quickemu project ğŸ’ª
          We'll try to review your pull request soon â²

          In the meantime you might want to join the [Wimpys World Discord](https://wimpysworld.io/discord) where
          we have a large community of Linux ğŸ§ enthusiasts and passionate open source
          developers ğŸ§‘â€ğŸ’»

          You might also be interested in following [Wimpys World Twitch ğŸ“¡ channel](https://twitch.tv/WimpysWorld)
          where Wimpy streams let's code video, including this project, several
          times a week. A back catalog of past live stream and other Linux related content
          is available on [Wimpys World YouTube ğŸ“º channel](https://youtube.com/WimpysWorld).'
